version: '3.7'

services:
  api:
    build: ./api
    # command: gunicorn --bind 0.0.0.0:5000 api:app
    # command: python api.py
    command: flask run --host=0.0.0.0
    ports:
      - 5005:5000
  bert:
    build: ./bert-server/UNCASED_EN_BASE
    expose:
      - 5555
      - 5556
    ports:
      - 8125:8125
  frontend:
    build: ./frontend
    command: python -m http.server 7000
    ports:
      - 7000:7000
    
      
